# Generated by Django 4.1.4 on 2022-12-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'recipes'},
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='User',
            new_name='user',
        ),
    ]
